/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_studyjni_hello_HelloJNI */

#ifndef _Included_com_studyjni_hello_HelloJNI
#define _Included_com_studyjni_hello_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_studyjni_hello_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studyjni_hello_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
